description: AzureManagedMachinePool is the Schema for the azuremanagedmachinepools API.
properties:
  apiVersion:
    description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
    type: string
  kind:
    description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
    type: string
  metadata:
    properties:
      annotations:
        additionalProperties:
          type: string
        description: 'Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations'
        type: object
      labels:
        additionalProperties:
          type: string
        description: 'Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        type: object
      name:
        description: 'Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names'
        type: string
      namespace:
        description: "Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \"default\" namespace, but \"default\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty. \n Must be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"
        type: string
    type: object
  spec:
    description: AzureManagedMachinePoolSpec defines the desired state of AzureManagedMachinePool.
    properties:
      mode:
        description: 'Mode - represents mode of an agent pool. Possible values include: System, User.'
        enum:
        - System
        - User
        type: string
      name:
        description: Name - name of the agent pool. If not specified, CAPZ uses the name of the CR as the agent pool name.
        type: string
      osDiskSizeGB:
        description: OSDiskSizeGB is the disk size for every machine in this agent pool. If you specify 0, it will apply the default osDisk size according to the vmSize specified.
        format: int32
        type: integer
      providerIDList:
        description: ProviderIDList is the unique identifier as specified by the cloud provider.
        items:
          type: string
        type: array
      sku:
        description: SKU is the size of the VMs in the node pool.
        type: string
    required:
    - mode
    - sku
    type: object
type: object
