name: preview-website

on:
  pull_request:
    branches:
      - "*"

concurrency:
  group: '${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
        id: go

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install yq
        run: |
          curl -fsSL -o yqq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
          chmod +x yqq
          sudo mv yqq /usr/local/bin/yqq
          pip3 install yq

      - name: Install Hugo
        run: |
          curl -fsSL -o hugo_extended.deb https://github.com/gohugoio/hugo/releases/download/v0.87.0/hugo_extended_0.87.0_Linux-64bit.deb
          sudo dpkg -i hugo_extended.deb
          rm hugo_extended.deb

      - name: Install Hugo Tools
        run: |
          curl -fsSL -o hugo-tools https://github.com/appscodelabs/hugo-tools/releases/download/v0.2.21/hugo-tools-linux-amd64
          chmod +x hugo-tools
          sudo mv hugo-tools /usr/local/bin/hugo-tools

      - name: Update docs
        env:
          GOOGLE_CUSTOM_SEARCH_API_KEY: ${{ secrets.GOOGLE_CUSTOM_SEARCH_API_KEY }}
        run: |
          npm install
          make docs
          make gen-draft

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QA }}'
          projectId: kubedb-new-e7965
          # target: kubedb-new-e7965
          # entryPoint: '.'
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
